### ISSUE TITLE
parse "multi" genbank file

### ISSUE THREAD

**Issue by audy** [bioruby/bioruby#106]
This is a combination bug report and feature request.

The current GenBank parser only parses singlular GenBank records.

__Bug__: It *will* parse multi-GenBank files, silently concatenating the genomic sequences. I'm not sure if this was intentional. It doesn't make sense to merge contigs together. Or does it? I might be missing something about GenBank. At the very least, `Bio::GenBank` should raise some sort of Exception when a second `LOCUS` is encountered.

__Feature Request__: add a separate method/class for parsing multi-GenBank records. This can be as simple as:

```ruby
class MultiGenBank
  def parse data
    data.split("\nLOCUS").map { |x| Bio::GenBank.new(x) }
  end
end
```

**Comment by ngoto** [comment]
Bio::FlatFile should be used for reading multiple entries in a file.
For a string, please use StringIO and Bio::FlatFile.

```ruby
require 'stringio'
Bio::FlatFile.open(StringIO.new(str)) do |ff|
  ff.each do |e|
    p e.entry_id
  end
end
```

How to treat "broken" data is still an open question.
Currently, Bio::GenBank and most parser classes in BioRuby does not raise errors with any input data, because most data formats are not strictly defined and it is hard to define errors.

**Comment by audy** [comment]
I missed that. Thanks!
